# Generated by Django 2.2.12 on 2022-04-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0003_auto_20220405_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='image',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='rent',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='title',
        ),
        migrations.AddField(
            model_name='todo',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
